export const accs = [{ 
  id: "sayed2-3125698",
  img: "./image/accs/accs-2.jpg",
  name: "Classic Hybrid Chain",
  price: "200",
  sale: "17",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  id: "sayed2-3125698",
  img: "./image/accs/accs-1.jpg",
  name: "Men Hybrid Chain",
  price: "150",
  sale: "5",
  discr: "Men's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  id: "sayed2-453543",
  img: "./image/accs/accs-3.jpg",
  name: "Leather glasses case",
  price: "170",
  sale: "9",
  discr: "Classic Leather glasses case Best quality at the lowest price with",
},{ 
  id: "sayed2-4863874",
  img: "./image/accs/accs-4.jpg",
  name: "Green glasses case",
  price: "100",
  sale: "12",
  discr: "Classic Leather glasses case Best quality at the lowest price with",
},{ 
  id: "sayed2-727227",
  img: "./image/accs/accs-5.jpg",
  name: "Orange glasses case",
  price: "150",
  sale: "15",
  discr: "Orange glasses case Best quality at the lowest price with",
},{ 
  id: "sayed2-4534534",
  img: "./image/accs/accs-6.jpg",
  name: "Classic Hybrid Chain",
  price: "250",
  sale: "3",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  id: "sayed2-54453",
  img: "./image/accs/accs-7.jpg",
  name: "black glasses case",
  price: "550",
  sale: "55",
  discr: "Black glasses case Best quality at the lowest price with",
},{ 
  id: "sayed2-453348",
  img: "./image/accs/accs-8.jpg",
  name: "Red glasses case",
  price: "550",
  sale: "30",
  discr: "Red glasses case Best quality at the lowest price with",
},{ 
  id: "sayed2-453484",
  img: "./image/accs/accs-9.jpg",
  name: "Classic Hybrid Chain",
  price: "50",
  sale: "2",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  id: "sayed2-4836443",
  img: "./image/accs/accs-11.jpg",
  name: "Classic Glasses Clener",
  price: "30",
  sale: "15",
  discr: "Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  id: "sayed2-453434",
  img: "./image/accs/accs-12.jpg",
  name: "Glasses Clener",
  price: "120",
  sale: "30",
  discr: "Glasses Clener Best quality at the lowest price with",
},{ 
  id: "sayed2-45343444",
  img: "./image/accs/accs-13.jpg",
  name: "Eyeglass cleaning wipe",
  price: "15",
  sale: "5",
  discr: "Eyeglass cleaning wipe Best quality at the lowest price with",
},{ 
  id: "sayed2-7972729",
  img: "./image/accs/accs-14.jpg",
  name: "Classic Hybrid Chain",
  price: "250",
  sale: "15",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  id: "sayed2-452452",
  img: "./image/accs/accs-15.jpg",
  name: "Classic Hybrid Chain",
  price: "50",
  sale: "10",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  id: "sayed2-436439",
  img: "./image/accs/accs-16.jpg",
  name: "Eyeglass cleaning wipe",
  price: "25",
  sale: "5",
  discr: "Eyeglass cleaning wipe Best quality at the lowest price with",
},{ 
  id: "sayed2-383648",
  img: "./image/accs/accs-17.jpg",
  name: "wight glasses case",
  price: "550",
  sale: "30",
  discr: "wight glasses case Best quality at the lowest price with",
},{ 
  id: "sayed2-4396854",
  img: "./image/accs/accs-18.jpg",
  name: "Goold Classic Hybrid Chain",
  price: "1550",
  sale: "20",
  discr: "Women's Classic Hybrid Chain Best quality at the lowest price with",
},{ 
  id: "sayed2-543984",
  img: "./image/accs/accs-19.jpg",
  name: "Black glasses case",
  price: "550",
  sale: "30",
  discr: "Black glasses case Best quality at the lowest price with",
},{ 
  id: "sayed2-287564",
  img: "./image/accs/accs-20.jpg",
  name: "Blue glasses case",
  price: "550",
  sale: "30",
  discr: "Blue glasses case Best quality at the lowest price with",
},{ 
  id: "sayed2-789452",
  img: "./image/accs/accs-21.jpg",
  name: "Black glasses case",
  price: "550",
  sale: "30",
  discr: "Black glasses case Best quality at the lowest price with",
},{ 
  id: "sayed2-495237",
  img: "./image/accs/accs-23.jpg",
  name: "Eyeglass cleaning wipe",
  price: "55",
  sale: "10",
  discr: "Eyeglass cleaning wipe Best quality at the lowest price with",
}]