export const products = [{ 
  id: "sayed-264952",
  img: "./image/prodcts/men/men-round-eyeglasses-1.jpg",
  name: "Round EyeGlasses black men`s",
  lens: "Anti-Reflective",
  price: "1500",
  sale: "33",
  type: "men",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/sunglasses/sun-round-eyeglasses-2.jpg",
  name: "SunGlasses for men`s",
  lens: "Polycarbonate Lenses",
  price: "2500",
  sale: "30",
  type: "sun",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/sunglasses/sun-round-eyeglasses-3.jpg",
  name: "SunGlasses for men`s",
  lens: "Polycarbonate Lenses",
  price: "1750",
  sale: "20",
  type: "sun",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/sunglasses/sun-round-eyeglasses-1.png",
  name: "SunGlasses for men`s",
  lens: "Polycarbonate Lenses",
  price: "1500",
  sale: "25",
  type: "sun",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/children/chil-round-eyeglasses-2.png",
  name: "EyeGlasses for children`s",
  lens: "Bifocal Lenses",
  price: "1000",
  sale: "25",
  type: "chil",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/children/chil-round-eyeglasses-3.png",
  name: "EyeGlasses for children`s",
  lens: "Bifocal Lenses",
  price: "1000",
  sale: "25",
  type: "chil",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/children/chil-round-eyeglasses-1.png",
  name: "EyeGlasses for children`s",
  lens: "Bifocal Lenses",
  price: "1000",
  sale: "25",
  type: "chil",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/women/women-round-eyeglasses-1.png",
  name: "EyeGlasses for women`s",
  lens: "Single Vision Lenses",
  price: "20000",
  sale: "20",
  type: "women",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/women/women-round-eyeglasses-3.png",
  name: "EyeGlasses women`s",
  lens: "Bifocal Lenses",
  price: "2000",
  sale: "30",
  type: "women",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/women/women-round-eyeglasses-2.png",
  name: "EyeGlasses women`s",
  lens: "Bifocal Lenses",
  price: "2000",
  sale: "60",
  type: "women",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/men/men-round-eyeglasses-2.jpg",
  name: "EyeGlasses head women`s",
  lens: "Blue-Cut",
  price: "860",
  sale: "20",
  type: "men",
},{ 
  id: "sayed-287463",
  img: "./image/prodcts/men/men-round-eyeglasses-4.jpg",
  name: "EyeGlasses gold men`s metal",
  lens: "Anti-Reflective",
  price: "7000",
  sale: "60",
  type: "men",
},{ 
  id: "sayed-743652",
  img: "./image/prodcts/men/men-round-eyeglasses-5.jpg",
  name: "Sunglasses white men`s metal",
  lens: "Anti-Reflective",
  price: "6000",
  sale: "80",
  type: "men",
},{ 
  id: "sayed-685325",
  img: "./image/prodcts/men/men-round-eyeglasses-6.jpg",
  name: "Sunglasses red men`s",
  lens: "Anti-Reflective",
  price: "15000",
  sale: "90",
  type: "men",
},{ 
  id: "sayed-375642",
  img: "./image/prodcts/men/men-round-eyeglasses-3.jpg",
  name: "Sunglasses gold men`s",
  lens: "Anti-Reflective",
  price: "500",
  sale: "20",
  type: "men",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/women/women-round-eyeglasses-4.png",
  name: "Round EyeGlasses women`s",
  lens: "Bifocal Lenses",
  price: "2020",
  sale: "70",
  type: "women",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/women/women-round-eyeglasses-5.png",
  name: "EyeGlasses women`s",
  lens: "High-Index Lenses",
  price: "20000",
  sale: "60",
  type: "women",
},{ 
  id: "sayed-219463",
  img: "./image/prodcts/women/women-round-eyeglasses-6.png",
  name: "EyeGlasses women`s",
  lens: "High-Index Lenses",
  price: "5000",
  sale: "65",
  type: "women",
}];